### ISSUE TITLE
[Bug]: An index signature parameter type must be either 'string' or 'number'.

### ISSUE THREAD

**Issue by Mukesh-HM** [winstonjs/logform#253] opened 2023-02-23 08:47 UTC
### The problem

node_modules/logform/index.d.ts:14:4 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

14   [key: string | symbol]: any;

### What version of Logform presents the issue?

v2.5.1

### What version of Node are you using?

v16.13.2

### If this is a TypeScript issue, what version of TypeScript are you using?

v3.9.7

### Additional information

logform as a dependency of winston

### 🔎 Search Terms

logform

**Comment by andykais** [comment] 2023-02-27 17:08
this is also an issue with typescript version `3.4.5` and logform version `2.4.2`

**Comment by emmanuelgautier** [comment] 2023-02-28 17:39
This issue exists for typescript version `4.1.5` and logform version `2.5.1`  as well

**Comment by wbt** [comment] 2023-02-28 23:07
Closing as duplicate of #244; see discussion and workarounds there.

**Closed by wbt** 2023-02-28 23:07 UTC
