### ISSUE TITLE
PrettyPrint format function logging Symbols (level, message)

### ISSUE THREAD

**Issue by pflugs30** [winstonjs/logform#31] opened 2018-05-10 19:53 UTC
This issue was previously reported on the main Winston issues list as [#1308](https://github.com/winstonjs/winston/issues/1308).  Moving it here since the `prettyPrint` function is actually a part of this repository.

I'm running the sample code under the [Combining Formats](https://github.com/winstonjs/winston#combining-formats) section.  I've created a brand new Node project, and Winston is the only package installed.  I created a new `index.js` file, and it only contains the code in the *Combining Formats* section.  When I execute the code, I see the following log output:

```
{ level: 'info',
  message: 'What time is the testing at?',
  label: 'right meow!',
  timestamp: '2018-05-10T00:52:02.906Z',
  [Symbol(level)]: 'info' }
```

According to the text in the section, I should see:

```
{ level: 'info',
  message: 'What time is the testing at?',
  label: 'right meow!',
  timestamp: '2018-05-10T00:52:02.906Z' }
```

According to my testing (using the latest version of Winston), the `[Symbol(level)]: 'info'` part is coming from the `prettyPrint` function invocation.  I looked at the function itself, and I couldn't immediately see why it logged the `Symbol` portion.  Is there a defect with the function or is it part of the configuration?

**Comment by pito-svk** [comment] 2018-05-13 17:04
Same issue for me.

**Comment by indexzero** [comment] 2018-05-24 06:17
`winston` uses Symbols under the covers – see [winston docs](https://github.com/winstonjs/winston#streams-objectmode-and-info-objects). Clearly those symbols are getting picked up by `util.inspect` from `node` (which is what `prettyPrint` uses). Open to other suggestions for libraries that allow for more customizable printing.

**Comment by max7z** [comment] 2018-07-19 10:50
Is there workaround for this issue? Is it possible to remove [Symbol(level)] and [Symbol(message)] from final output?

**Comment by justinpincar** [comment] 2018-09-03 07:56
The `util.inspect` line for `prettyPrint()` - https://github.com/winstonjs/winston/blob/af8f96f18d8af77625d1c44149ddef3039bff8b2/lib/winston/common.js#L164.

It looks like the display of symbols is controlled by the `showHidden` option - so would just need that merged in. https://nodejs.org/api/util.html#util_util_inspect_object_options

Maybe support passing in additional options as an arg to `prettyPrint()` to support both use cases?

**Comment by DABH** [comment] 2018-09-03 21:41
We do specify `showHidden: false` actually... I've been looking into this for an hour and can't figure out why we're seeing those Symbols; I really think they should be getting stripped by `util.inspect`.  I opened https://github.com/nodejs/node/issues/22678 -- let's see if this is a `util.inspect` issue or if I'm missing something obvious here.  Once that issue is resolved we can figure out how to proceed -- I can see either manually stripping those two symbols, or finding an alternative to `util.inspect`.

**Comment by DABH** [comment] 2018-09-03 21:41
(And, to avoid confusion, [this](https://github.com/winstonjs/logform/blob/master/pretty-print.js#L14) is the right place where we're calling inspect in 3.0)

**Comment by DABH** [comment] 2018-09-03 21:50
Ok, unsurprisingly not a Node bug, turns out the relevant Symbols here from `triple-beam` are enumerable.  But seems like `enumerable` should be `false` by default? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty So why do they become enumerable?  @indexzero any ideas?

**Comment by DABH** [comment] 2018-09-03 22:04
Seems after here https://github.com/winstonjs/winston/blob/master/lib/winston/logger.js#L155 already info[LEVEL] is enumerable... so I guess enumerability is not preserved across the = operator, or something like that?  So we are not using triple-beam correctly or something?  Need some deep JS expertise here ^_^

**Comment by BridgeAR** [comment] 2018-09-03 22:15
@DABH as soon as a property is defined as not enumerable, it will stay that way until redefined. That is not the case by the "regular" assign with `a = 'foo'`.

 Without looking at the code the symbol is likely added to the object like:

```js
const level = Symbol('level')
const obj = {}
obj[level] = 'foobar'
```

It has to be assigned as:

```js
const level = Symbol('level')
const obj = {}
Object.defineProperty(obj, level, { value: 'foobar', enumerable: false, configurable: true, writable: true })
```

I am not sure if the latter two should be true or not as that depends on how this is used in winston.

**Comment by DABH** [comment] 2018-09-03 22:25
Thanks very much @BridgeAR for the help!  We did determine `util.inspect` is not at fault, the problem is our supposedly non-enumerable Symbols becoming enumerable on assignment.

We are defining the symbols in the `triple-beam` module [here](https://github.com/winstonjs/triple-beam/blob/master/index.js), e.g. as
```js
Object.defineProperty(exports, 'LEVEL', {
  value: Symbol.for('level')
});
```
(`enumerable` should be `false` by default?).  Then in the main `winston` code we're doing something like
```js
const { LEVEL } = require('triple-beam');
...
info[LEVEL] = level;
```
and after that `info[LEVEL]` is enumerable.  Part of the intent of `triple-beam` seems like to be able to use this nice shorthand assignment while preserving non-enumerability.  But is that really not possible, i.e. do we really always have to do something like `Object.defineProperty(info, LEVEL, { value: level, enumerable: false, configurable: true, writable: true });`?  That's a lot uglier, though we can wrap it in a helper function -- but kind of defeats some of the goals of `triple-beam` and not as nice as using plain assignment :)  Would appreciate your expertise on what will/won't work here and if you have recommendations/best practices to share!  Thanks again!

**Comment by BridgeAR** [comment] 2018-09-03 22:29
@DABH the first part is not relevant for `info`.

You only assign a regular symbol property to info when doing:

```js
info[LEVEL] = level
```

Instead, you have to define it to be non-enumerable at this point:

```js
const { LEVEL } = require('triple-beam')
...
Object.defineProperty(info, LEVEL, { value: level })
```

**Comment by DABH** [comment] 2018-09-03 22:36
Cool, makes sense (TIL!).  I think I have clarity now on the Symbol/JS side of things -- will try to chat with @indexzero soon to discuss what we want to do to resolve the original issue (we can go through winston and make a bunch of changes like ^that, or manually strip the triple-beam symbols at some point during log or format by default, or maybe some other option).

**Comment by indexzero** [comment] 2018-09-17 18:32
The benchmarks for this are not great. 

``` js
const run = bench([
  function enumerable(done) {
    const obj = {};
    obj[LEVEL] = 'foo';
    done();
  },
  function nonenumerable(done) {
    const obj = {};
    Object.defineProperty(obj, LEVEL, { value: 'foo', enumerable: false });
    done();
  }
], 1000);

run(run);
```

shows us:

```
$ node index.js 
enumerable*1000: 0.584ms
nonenumerable*1000: 0.798ms
enumerable*1000: 0.198ms
nonenumerable*1000: 1.263ms
```

Basically anywhere from **twice as slow to 10x slower.** As such I think we are better off stripping these properties from the info objects in the `prettyPrint` format instead of incurring this cost on the entire `winston` system.

**Closed** 2018-09-21 21:29 UTC
Labels: bug

**Comment by DABH** [comment] 2018-09-21 21:30
Fixed at last on `master`, and will go out in the next `npm` release.  Thanks all!

Note the fix is just for `prettyPrint` so if you see issues with other formatters feel free to open an issue or a similar PR to ^^

**Comment by muhajirframe** [comment] 2018-10-24 10:04
Hey, is it released?

**Comment by Kaisle** [comment] 2018-11-02 20:53
When do you plan on releasing this?

**Comment by amitkirdatt** [comment] 2018-11-12 15:52
The change is available in logform [1.10.0](https://github.com/winstonjs/logform/compare/1.10.0...master). However, winston's lock file is at [1.9.1](https://github.com/winstonjs/winston/blob/master/package-lock.json#L3745). We need winston to pull in the change and release.

**Comment by amitkirdatt** [comment] 2018-11-12 16:32
Winston PR [here](https://github.com/winstonjs/winston/pull/1529) to upgrade to logform 1.10.0

**Comment by paulxtiseo** [comment] 2018-12-31 02:54
I am using Winston v3.1.0, which seems to be using logform v1.9.1. But, seems like the fix is ion the newer v2? Any idea when will Winston gain the fix?

**Comment by deekayw0n** [comment] 2019-01-31 22:16
Hi All (attn: @DABH) - Now running v3.2.1 and still see the pesky Symbol() representations of all attributes coming from our prettyPrint format function. 

Is it possible that this issue was resolved when format is defined as an attribute to winston.createLogger() but not when its an attribute in winston.transports? We define it at this level because our logger has multiple transports each with their own format - see code snippet below:

```
const winston = require('winston');
const path = require('path');

const { createLogger, format, transports } = winston;
const debugOnly = winston.format(info => (info.level === 'debug' ? info : false));

const winstonLogger = createLogger({
  transports: [
    new transports.Console({
      level: 'info',
      format: format.prettyPrint({ colorize: true }),
    }),
    new transports.File({
      level: 'debug',
      filename: path.join(logLocation || '/tmp', '/debug.log'),
      maxSize: '10m',
      format: format.combine(
        debugOnly(),
        format.timestamp(),
        format.printf(i => `${i.timestamp} ${i.message}`),
      ),
    }),
  ],
});

```

**Comment by indexzero** [comment] 2019-01-31 22:49
Howdy! This is indeed a bug, apologies. In the future it would be appreciated if you looked at open PRs first as it will help answer your question before it is asked.

In this case I am referring to #74 which should correct the aberrant behavior. 

I am locking this issue to discourage follow-on comments to a previously closed issue. Regressions should be treated as new issues 😈
