### ISSUE TITLE
Errors format throws TypeError

### ISSUE THREAD

**Issue by limzykenneth** [winstonjs/logform#77] opened 2019-02-03 00:24 UTC
When following [example](https://github.com/winstonjs/logform#errors) outlined in the readme. I get the following error:
```
TypeError: Cannot destructure property `stack` of 'undefined' or 'null'.
    at Format.module.exports.format [as transform] (.../node_modules/logform/errors.js:14:25)
```
It is traceable back to [this line](https://github.com/winstonjs/logform/blob/master/errors.js#L14). More specifically to the second argument of `format`'s callback: `{ stack }`. When I call `errorsFormat.transform(new Error('Oh no!'));` the second argument in the callback will attempt to destructure whatever is passed and fine the `stack` property but since there is only one argument passed, it cannot destructure the second argument of `undefined`.

That is my analysis anyway, so I might be wrong but doing something like `errorsFormat.transform(new Error('Oh no!'), new Error('Oh no!'));` while pointless, it works.

**Comment by DABH** [comment] 2019-03-11 23:14
Thanks for report and sorry for slow reply!  Closing as duplicate of #80 , but this should be a quick fix.

**Closed by DABH** 2019-03-11 23:14 UTC
