### ISSUE TITLE
lazy-load does not play well with nexe

### ISSUE THREAD

**Issue by jd-carroll** [winstonjs/logform#66] opened 2018-12-03 21:45 UTC
We are facing an issue using this module with a [nexe](https://github.com/nexe/nexe) bundled project.  Essentially nexe does not support any type of [dynamic module imports](https://github.com/winstonjs/logform/blob/master/index.js#L28).

Is there any specific reason why the transports are setup lazily?

**Comment by marcelfalliere** [comment] 2019-01-31 10:35
Same here. Our project bundle with [parcel](https://parceljs.org/) has problem starting because it cannot find `colorize` because it is imported dynamicly by `logform`. Culprit piece of code :

```
/*
 * @api private
 * method {function} exposeFormat
 * Exposes a sub-format on the main format object
 * as a lazy-loaded getter.
 */
function exposeFormat(name, path) {
  path = path || name;
  Object.defineProperty(format, name, {
    get() {
      return require(`./${path}.js`);
    },
    configurable: true
  });
}
```

Parcel does not support dynamic loading. Anyway, just pilling up on @jd-carroll issue.

**Comment by iameli** [comment] 2019-05-01 04:14
Hm yeah. Winston is quite useful for running in a variety of environments, it's a shame that it can't be built with Parcel and such.

**Comment by DABH** [comment] 2019-05-01 04:38
logform / winston specify `browser` fields in package.json which is what bundlers like `webpack` use instead of the `main` fields.  The versions of the files in `browser` do not use dynamic imports and so should be fine for your use cases
https://github.com/winstonjs/logform/blob/master/package.json
However, it seems `parcel`, `nexe`, etc. (I am not hip with all the bundlers unfortunately) are preferring the `main` field instead of the `browser` field, which feels like a bug with them since this is exactly what that field was intended for.  Do you know if those bundlers have a similar/analogous field we should be setting in our package.json's?  Or is there a way to make them not ignore `browser`?

**Comment by DABH** [comment] 2019-05-23 04:04
Potentially fixed in https://github.com/winstonjs/winston/pull/1640 but need to test...

**Comment by JakeDluhy** [comment] 2019-08-22 02:08
Not sure if this helps anyone, but I was having this problem using winston with `electron` (specifically from the main process, not the renderer). I was able to fix it by adding
```
resolve: {
  alias: {
    logform$: path.resolve(__dirname, 'node_modules', 'logform', 'dist', 'browser'),
  },
},
```
to my main process webpack config.

**Comment by 55Cancri** [comment] 2020-04-04 14:48
Any update to this using parcel? I am using aws-cdk with parcel-bundler@^1 and failing for all format functions including `combine`.

**Closed** 2022-10-07 01:36 UTC
